import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Shahrier',
      email: 'admin@gmail.com',
      password: bcrypt.hashSync('1234'),
      isAdmin: true,
    },
    {
      name: 'Shahrier',
      email: 'admin2@gmail.com',
      password: bcrypt.hashSync('1234'),
      isAdmin: false,
    },
  ],
  products: [
    {
      id: 1,
      name: 'Free Shirt',
      type: 'trends',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      id: 2,
      name: 'Fit Shirt',
      type: 'trends',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Raymond',
      rating: 4.3,
      numReviews: 4,
      countInStock: 25,
      description: 'A popular shirt',
    },
    {
      id: 3,
      name: 'Slim Shirt',
      type: 'trends',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 85,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 11,
      countInStock: 14,
      description: 'A popular shirt',
    },
    {
      id: 4,
      name: 'Golf Pant',
      type: 'trends',
      slug: 'golf-pant',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 3.8,
      numReviews: 4,
      countInStock: 32,
      description: 'A popular pants',
    },
    {
      id: 5,
      type: 'trends',
      name: 'Fit Pant',
      slug: 'fit-pant',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 90,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 18,
      description: 'A popular pants',
    },
    {
      id: 6,
      name: 'Classic Pant',
      type: 'trends',
      slug: 'classic-pant',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 75,
      brand: 'Casely',
      rating: 4.7,
      numReviews: 15,
      countInStock: 16,
      description: 'A popular pants',
    },
  ],
};

export default data;
